### ISSUE TITLE
performance of switching between reactions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#17]
@ycarpenterphet reported this via email for 1.0.0-dev.13:

>  When playing the game (iPad2, iOS7), loading each subsequent question (by pressing Next) seems to take a very long time, and that lag/load time seems to increase as the game is played for a longer period of time. 
> 
> The lag is minimal on chrome/OSX 10.9, but it’s possibly increasing in length as well (difficult to tell with the shorter lag time), so I wonder if this is a memory issue?
> 
> Regardless, the substantial time lag on iPad is very noticeable and problematic - could you look into this?

**Comment by pixelzoom** [comment]
Here's a dev version demonstrating the performance when switching between Challenges in the Game:
http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-dev.21/reactants-products-and-leftovers_en.html

Please let me know if this performance is acceptable.

**Comment by pixelzoom** [comment]
@ycarpenterphet and @ariel-phet Here's a dev version demonstrating the performance when switching between Challenges in the Game:
http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-dev.21/reactants-products-and-leftovers_en.html

Please let me know if this performance is acceptable.

**Comment by pixelzoom** [comment]
@ycarpenterphet if the performance of 1.0.0-dev.21 is acceptable, please close this issue. Otherwise reassign it to me with a description of what needs to be improved. Thanks!

**Comment by ariel-phet** [comment]
@ycarpenterphet and @pixelzoom -- I tested the sim out and it seemed to be running well on iPad2. Nice work Chris!
