### ISSUE TITLE
improve performance of level selection in Game

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#25]
Level selection performance is acceptable, but could be improved. This can be done by reusing 1 instance of each NITROGLYCERIN molecule node, instead of creating new molecule nodes when challenges are created (in ReactionFactory).

**Comment by pixelzoom** [comment]
This was implemented in a8f500025e7268f838b7b50574341a0082c46673. But it exposed a problem with gradients in Scenery 0.1, see https://github.com/phetsims/scenery/issues/335#issuecomment-68563261.  There was no good workaround for this, so I backed out this enhancement. We'll have to live with this for RPAL 1.0, but may revisit for a future release.

**Comment by pixelzoom** [comment]
@ycarpenterphet please confirm that you're OK with deferring this. We can revisit for a future release, some time after Scenery 0.2 is released.

**Comment by pixelzoom** [comment]
phetsims/scenery#335 is fixed, so we could revisit this if/when necessary.

**Comment by pixelzoom** [comment]
As described in https://github.com/phetsims/reactants-products-and-leftovers/issues/25#issue-53285185, the performance of the game could likely be improved.  But there have been no complaints about performance.  My recommendation would be to defer this, not include it in "Summer 2015 redeploy".

@ariel-phet If you agree, please remove the "Summer 2015 redeploy" label and unassign.

**Comment by pixelzoom** [comment]
@ariel-phet ping.

**Comment by ariel-phet** [comment]
Agreed.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/reactants-products-and-leftovers/issues/25#issuecomment-68572389, I said:
> This was implemented in a8f500025e7268f838b7b50574341a0082c46673. But it exposed a problem with gradients in Scenery 0.1, see https://github.com/phetsims/scenery/issues/335#issuecomment-68563261.  There was no good workaround for this, so I backed out this enhancement. We'll have to live with this for RPAL 1.0, but may revisit for a future release.

https://github.com/phetsims/scenery/issues/335 is resolved, so it's likely that the workaround may now be applied.

**Comment by pixelzoom** [comment]
Tested this again and it's plenty responsive.  I see no reason to ever do this, so closing.
