### ISSUE TITLE
Slight lag changing numerical value when using spinners on iPad

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/reactants-products-and-leftovers#27]
Test device: iPad 2
Operating System: iOS 7.1
Browser: Safari
Problem description:
There exist a very slight delay when using the spinners to change the number of reactants or products.
The delay is only a second, but can become a hassle when clicking fairly fast.

Severity: Low

Troubleshooting information (do not edit):
Name: Reactants, Products and Leftovers
URL: http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-dev.23/reactants-products-and-leftovers_en.html
Version: 1.0.0-dev.23
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D167 Safari/9537.53
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: disabled

**Comment by pixelzoom** [comment]
Do you see this delay if you tap and immediately release one of the spinner's arrow buttons?  If you are holding the arrow button down, then there will be a 400 ms delay before the value starts changing.

**Comment by pixelzoom** [comment]
@orejolaphet I don't see anything close to a 1-second delay on iPad2 with iOS 8.1.2.  Can you please test on a device with iOS 8.1.2 to confirm?  And could you please answer the question in the comment immediately above. Thanks.

**Comment by pixelzoom** [comment]
@ycarpenterphet Could you please evaluate the performance of the test platform (iPad2 + iOS7)? It sounds like it's specific to iOS7, and is still acceptable. If that's the case, I recommend closing this as "won't fix".

**Comment by ycarpenterphet** [comment]
Looks fine to me on iPad2/iOS 7.0.4.

Although there is a short delay after the spinner arrow is tapped, this is barely perceptible when the spinner is tapped multiple times to increase or decrease the coefficients. Based on interviews, this very small delay would likely go unnoticed by most users/students, since they are also working on counting at the same time.

Closing.
