### ISSUE TITLE
postmortem after publication

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/reactants-products-and-leftovers#29]
We will plan to do a post-mortem on this sim after it is published

@pixelzoom @ycarpenterphet and @ariel-phet should definitely be involved

Assigning to @pixelzoom if he thinks any other parties should attend the postmortem

**Comment by ariel-phet** [comment]
@pixelzoom please reassign to me after your suggestions if anyone else should attend

**Comment by pixelzoom** [comment]
For Java/Flash sims, the entire team typically attended the postmortem. So that would add Trish, Robert, Kathy, Oliver O, and Bryan Y.  Since this was a port (and a first HTML5 postmortem), I don't know if that many people is necessary or desirable.  Maybe leave invite them and leave it up to them whether to attend?... I'll leave it up to @ariel-phet and @ycarpenterphet to decide.

**Comment by samreid** [comment]
Not sure which members of the design team should attend (though I agree generally anyone with a significant involvement in the sim should attend the postmortem), but I think it is important to have *at least* one QA team member as part of the postmortem.

**Comment by ariel-phet** [comment]
@samreid -- we can see about that. Although I think that would be handy, I don't think we want to keep them at such a meeting for the full time (postmortems can be long and get into some details not relevant to the QA team). Perhaps we can arrange the process so that QA feedback is given early in the postmortem.

**Comment by ariel-phet** [comment]
@samreid let's move these comments over to https://github.com/phetsims/tasks/issues/147

**Comment by pixelzoom** [comment]
RPAL 1.0.0 is published. Postmortem can be scheduled anytime.

**Comment by ariel-phet** [comment]
- [ ]  **1. Schedule the meeting**
 - Require the entire sim team to participate, and optionally anyone else who had a significant involvement. Have the meeting as soon as possible after the sim is released, so that experiences are still fresh in everyone's mind. Allow sufficient time for the meeting, 1.5-2 hours.

 - [ ]  **2. Enlist a meeting moderator**
 - The moderator's job is to make sure the meeting runs efficiently, stays on point, and focuses on constructive (but not overly negative) critcism. The moderator can be someone not on the sim team, or in many cases the Development Coordinator. The moderator also documents the important points of the meeting.

 - [ ]  **3. Create github postmortem issue and postmortem google doc**
 - Create a github issue in the repository of the sim for which the postmortem is occuring. This checklist will should be copied into the issue.
 - Create a postmortem google doc and set phethelp as the owner. This google doc should live within the appropriate sim folder on google drive. 

 - [ ]  **4. Two successes and two improvements**
 - Require participants to bring a list of no more than 2 items that were done well during the project and no more than 2 items that could be improved upon. Limiting to 2 requires people to think critically about their experience.

 - [ ]  **5. Identifying the top five**
 - At the meeting, start by going around the room and having each person present their items (successes, then improvements). Make a list of these items, and note duplicates. Based on popularity, identify the top 5 success items and the top 5 items that need improvement.
  * Discuss the 5 success items first. Identify specific things that can be applied to future sims. Celebrate, pat each other on the back. Then move on to the harder part.
  * Discuss the 5 improvement items. Try to avoid getting personal. Discuss what was learned, and identify specific things that can be done to prevent these problems in the future. If anything needs more investigation, assign to specific individuals. 

 - [ ]  **6. Modifications to Look & Feel** 
 - Identify modifications to the PhET Look-&-Feel Guidelines. If applicable, based on what we learned during development of this sim, suggest revisions to the guidelines.
  * [HTML5 Look and Feel](https://docs.google.com/document/d/1Tv-VyI24g70ZixH99jujN2Sdm7DfoVFiPUo5P1bFWrY/edit#heading=h.97ziwh4gfhga)
  * [HTML5 Sim Design Elements] (https://docs.google.com/document/d/1SWgrtr1ZUrylYspOP57wo1SVVlYn8mjQNNR-XdmMa6Y/edit#heading=h.efdoz189j1ov)

- [ ]  **7. Sim checklist** 
- Review the "Sim checklist" (under development). Will be a "living" issue for each sim reposiory

- [ ]  **8. Action items** 
- Note important items in the postmortem github issue, and create issues for any tasks the require action (such as updating documents, leftover "todo's", etc. 

- [ ]  **9. Take home messages** 
- From the top 5 successes/improvements, decide what are the "take home messages" that would be useful to note in the future, and add these to the [HTML5 Postmortem Take Home Messages](https://docs.google.com/document/d/1hayLX0FbhYqGao-5xizAFU9kVBzqrW_RVX88Wk_C_Lc/edit#heading=h.krbf2d24bpav) google doc
- Report out at status meeting

**Comment by ycarpenterphet** [comment]
@ariel-phet, I've updated the postmortem document, highlighting some of the most useful, and (I feel) generalizable take-home messages from our list of successes and improvements. I'm passing this off to you now to place these into the checklist and take-home messages documents as appropriate, and check off the remaining items, above.

**Comment by pixelzoom** [comment]
@ariel-phet What's left to do here?

**Comment by ariel-phet** [comment]
@pixelzoom - a couple of things, I don't want to close this issue until a discussion of the sim checklist occurs (soon). Please just leave it assigned to me, it is on my radar to finish up.

**Comment by pixelzoom** [comment]
@ariel-phet status?

**Comment by ariel-phet** [comment]
Done, closing.
