### ISSUE TITLE
Sandwiches/Molecules screens: "After Reaction" text tracking different in FF

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/reactants-products-and-leftovers#31]
Here is Firefox 35.0 Sandwiches screen:
![reactants products and leftovers 1 0 0-rc 1 - mozilla firefox_2015-01-22_16-25-18](https://cloud.githubusercontent.com/assets/5090275/5866963/f2fbb566-a253-11e4-9e8d-cdf0b695afcf.png)

And the same browser Molecules screen:
![reactants products and leftovers 1 0 0-rc 1 - mozilla firefox_2015-01-22_16-25-28](https://cloud.githubusercontent.com/assets/5090275/5866964/f61c6d94-a253-11e4-98ce-1487b96fef1e.png)

The "Before Reaction" text also tracks slightly differently between the two screens but it is less noticeable.

Not sure if this is fixable, but since it is nearly identical text I thought there might be a way to make it consistent or identify the reason for the difference?

**Comment by oliver-phet** [comment]
Troubleshooting information (do not edit):
Name: Reactants, Products and Leftovers
URL: http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-rc.1/reactants-products-and-leftovers_en.html
Version: 1.0.0-rc.1
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1787x871
Pixel Ratio: 0.89552241563797/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by pixelzoom** [comment]
What does "text tracking" mean? Do you mean that there is more space to the left of the text in the button?

**Comment by pixelzoom** [comment]
@oliver-phet What does "text tracking" mean? Do you mean that there is more space to the left of the text in the button?

**Comment by oliver-phet** [comment]
The spacing between the letters is inconsistent. I've seen it before on FF, but since these two strings are so similar, I thought the cause might be something other than the quotes around Reaction. Neither really bugs me but I thought since the strings were so similar there might be another reason for the difference.

http://en.wikipedia.org/wiki/Letter-spacing

**Comment by pixelzoom** [comment]
@jonathanolson can you please comment on this? To this best of my knowledge, there's nothing we can do about this.

**Comment by jonathanolson** [comment]
It's curious, I'm able to reproduce on Chrome (Win7), but not on FF. It relates to SVG text settings (auto/optimizeLegibility/geometricPrecision) and resizing the strings to the correct bounds if necessary.

@oliver-phet, can you visit http://phetsims.github.io/scenery/tests/text-quality-test.html?lows and note whether you see jittering or display problems for the SVG geometricPrecision spacingAndGlyphs case? (right side 2nd from bottom). On Chrome Win7 I see a significant amount of jitter for that case.

We may need to re-evaluate what SVG text options are best across our range of supported devices, or optionally switch it based on browser (

**Comment by oliver-phet** [comment]
@jonathanolson On Chrome Win7 I see a lot of jitter for that case too.

On Firefox (35.0) the text is actually much less jittery. 

Screenshots don't really capture what I am seeing when the text is animating, but let me know if I can send any.

**Comment by pixelzoom** [comment]
Nothing we can do about this in RPAL 1.0, which uses Scenery 0.1. If and when it's addressed in Scenery 0.2, RPAL will benefit from the fix. Closing this issues as "won't fix".
