### ISSUE TITLE
Incorrect Question Mark Rendering in IE10

### ISSUE THREAD

**Issue by phet-steele** [phetsims/reactants-products-and-leftovers#32]
I noticed on the Windows 7 32-bit device I tested on that the top of the question marks appear thicker whenever the level select screen is viewed in IE10, whether by switching to the game screen, pressing continue after completing a level, or by pressing start over during a level. Once the mouse is moved they revert back to normal.

Viewing level select screen:
![rpal incorrect question](https://cloud.githubusercontent.com/assets/5863899/5880423/ad0a9746-a2f5-11e4-8425-a99ee7235912.png)

Once mouse is moved (for comparison):
![rpal correct question](https://cloud.githubusercontent.com/assets/5863899/5880434/bd91b0c2-a2f5-11e4-915c-9340760c823c.png)

Troubleshooting information:
Name: Reactants, Products and Leftovers
URL: http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-rc.1/reactants-products-and-leftovers_en.html
Version: 1.0.0-rc.1
Features missing: touch, webgl, fullscreen
Flags: msPointerEnabled
User Agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; AskTbORJ/5.15.15.36191; .NET4.0C; .NET4.0E)
Window: 1280x716
Pixel Ratio: 1/1
WebGL: unsupported

**Comment by pixelzoom** [comment]
@jonathanolson can you please comment on this? To the best of my knowledge, there's nothing we can do about this.

**Comment by jonathanolson** [comment]
Seems related to https://github.com/phetsims/scenery/issues/348. Will need to investigate to determine if there's anything we can do, or if there is an underlying bug (and whether it's present in 0.2).

**Comment by pixelzoom** [comment]
Nothing we can do about this in RPAL 1.0, which uses Scenery 0.1. If and when it's addressed in Scenery 0.2, RPAL will benefit from the fix.  Closing this issues as "won't fix".
