### ISSUE TITLE
Alignment of existing activities with HTML5 version

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/reactants-products-and-leftovers#34]
In preparation for future revisions to sim pages and targeted revision of activities, this lists all of the current RPAL activities and roughly how much revision they'll need of content and graphics to align with the HTML5 changes:
https://docs.google.com/spreadsheets/d/1kpoUudLRnAYCXT63SCtZyE3jJEUln48ntDJjYiqB5xE/edit#gid=0

**Comment by ycarpenterphet** [comment]
@ariel-phet I'm not sure whether there's a next stage, and/or if the spreadsheet could be a useful template as we start to do this for other activities (possibly with revision of the criteria - I just tried to give a first pass so that we can triage more effectively when activity revision happens in future; hopefully we can prioritize gold star activities, PhET-created materials, and easy-revisions first).

**Comment by ariel-phet** [comment]
This is being take care of as part of the HTML5 sim pages project, Closing
