### ISSUE TITLE
modify game flow so that "Try Again" is optional?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#37]
In phetsims/graphing-lines#47, it was requested to change the game flow so that the "Try Again" button automatically changed to "Check" when interacting with game.

In RPAL, the only thing that's interactive is the "Try Again" button.  The spinners are converted to read-only numbers (see screenshot below).  So we'd need to keep the spinners interactive.

![screenshot_567](https://cloud.githubusercontent.com/assets/3046552/9094012/d02e8da8-3b6c-11e5-9ff4-a10d1757f80e.png)

**Comment by pixelzoom** [comment]
In phetsims/graphing-lines#47 (comment), @ariel-phet stated that this should be "an open question for the design team". Assigning to @ariel-phet to decided who from the design team should be assigned to answer this question.

**Comment by pixelzoom** [comment]
Design question: In addition to clicking on the "Try Again" button... Specifically which interactions make the "Try Again" button disappear? Clicking *anywhere* on the screen? Or clicking on a spinner?

**Comment by pixelzoom** [comment]
I discussed the Area Builder game with @jbphet. The intent was to make the "Try Again" button disappear when the user did anything to change their answer. Is that also appropriate for this sim? If so, spinners will remain enabled, and the "Try Again" button will disappear when the user interactive with any spinner.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-lines/issues/47#issuecomment-135893275, @amanda-phet confirmed that the desired behavior for Area Builder and Graphing Lines is to make the "Try Again" button automatically disappear when the user changes their answer (or presses the "Try Again" button).  Since the impetus for this issues was to make behavior consistent across sims, I'm guessing that this sim should behave the same way. 

So the requirements for this sim are:
(1) keep the spinners interactive when "Try Again" button is visible, and 
(2) automatically replace the "Try Again" button with the "Check" button when the user interacts with a spinner or presses the "Try Again" button.

@ariel-phet I'll assigning this to myself and will address it soon (at the same time as the phetsims/graphing-lines#47).  If there the above requirements are not correct, please let me know asap.

**Comment by pixelzoom** [comment]
Game behavior has been changed as requested, see this dev version:

http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.0-dev.1/reactants-products-and-leftovers_en.html

@ariel-phet Would you mind verifying (or assigning to someone else) since the original team lead is

**Comment by pixelzoom** [comment]
Hi @amyh-phet, @ariel-phet tells me you're the new lead on this sim. Could you please review the fix for this issue? Thanks!

**Comment by amyh-phet** [comment]
Hi @pixelzoom.   The fix for the issue looks great.   It looked like the new game behavior is only applied to the first level of the game - correct?

**Comment by pixelzoom** [comment]
No, the change is applied to all levels of the Game -- if you interact with the spinner, the "Try Again" button automatically changes to "Check".  Are you seeing something different on Levels 2 & 3?

**Comment by amyh-phet** [comment]
@pixelzoom.   I just looked at the dev version again.   Looks good.   All levels have active spinners that change "Try Again" to "Check" if you interact with the spinner.   I think we are good!

**Comment by pixelzoom** [comment]
Great, thanks @amyh-phet. Closing this issue.
