### ISSUE TITLE
update QA credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#39]
The QA credits are currently:

`qualityAssurance: 'Oliver Orejola, Bryan Yoelin'`

@ariel-phet If applicable, please specify the revised QA credits, ordered alphabetically by last name.

**Comment by ariel-phet** [comment]
Steele Dalton, Bryce Griebenow, Elise Morgan, Oliver Orejola, Benjamin Roberts, Bryan Yoelin
