### ISSUE TITLE
Infinite Sandwiches!

### ISSUE THREAD

**Issue by phet-steele** [phetsims/reactants-products-and-leftovers#42]
Possibly a scenery issue @pixelzoom, but here it is.

In the "Sandwiches" and "Molecules" screens, the spinners have no min or max if the up/down arrows are clicked and held at the value one above the min or one below the max. In other words, using the custom sandwich reaction as an example, the values up top have a min of zero and max of 3. So it follows that if you click up once so the value is "1", then click and hold the down arrow, the values will go negative. For the opposite effect, starting at 0 and clicking up twice to "2", then clicking and holding the up arrow will make the numbers go quite large. This issue still holds true for the spinners along the bottom, except that the max has changed to 8, so you have to start at 7 before clicking and holding to get to large numbers. Both these cases cause some layout issues, seen in the video below. This issue holds true in the Game screen as well, but is more complicated and probably will be addressed simultaneously with this issue anyway.

https://drive.google.com/file/d/0B3HJopSo_QqLWUxnMk83UTBVOVE/view?usp=sharing

![hammer time](https://cloud.githubusercontent.com/assets/5863899/12123608/2907b508-b39f-11e5-9aa2-7230150a0a97.PNG)

Tested on Win 8.1, FF on my personal device.
Troubleshooting information:
Name: ‪Reactants, Products and Leftovers‬
URL: http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.0-rc.1/reactants-products-and-leftovers_en.html
Version: 1.1.0-rc.1 2015-12-13 01:01:52 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"HEAD"},"axon":{"sha":"fffc6c30","branch":"HEAD"},"babel":{"sha":"ac37bd17","branch":"master"},"brand":{"sha":"3b236d6f","branch":"HEAD"},"chipper":{"sha":"6735d265","branch":"HEAD"},"dot":{"sha":"5c39b7d8","branch":"HEAD"},"joist":{"sha":"2a5b44c4","branch":"HEAD"},"kite":{"sha":"84e84bca","branch":"HEAD"},"nitroglycerin":{"sha":"ef8c55a2","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"61a7c5fa","branch":"HEAD"},"reactants-products-and-leftovers":{"sha":"e0aa15ab","branch":"1.1"},"scenery":{"sha":"c0c08ec5","branch":"HEAD"},"scenery-phet":{"sha":"61d8e7ed","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"8d290320","branch":"HEAD"},"tandem":{"sha":"e98bd8c3","branch":"HEAD"},"vegas":{"sha":"e5d21051","branch":"HEAD"},"vibe":{"sha":"40a28182","branch":"HEAD"}}

**Comment by pixelzoom** [comment]
Problem reproduced in 1.1.0-rc.1.  It does not occur in 1.0.0 (on the PhET website), so this is a new problem. 

RPAL uses its own spinner type (`NumberSpinner`), which uses `scenery-phet.ArrowButton` for the arrow buttons.  Since 1.0.0 was published, the "fire-on-hold" feature was moved out of `scenery-phet.ArrowButton` and into `sun.PushButtonModel`.  See https://github.com/phetsims/scenery-phet/issues/71.  So I suspect that the problem is in how this feature was incorporated into PushButtonModel.  I spent a little time trying to isolate the issue, but it's not immediately obvious.  

This should most definitely be fixed before the sim is published.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/tasks/issues/376.

**Comment by ariel-phet** [comment]
@phet-steele can you also mark in the test matrix?

**Comment by phet-steele** [comment]
@ariel-phet I put the ticket number next to platforms I've seen have this issue with my own eyes.

**Comment by pixelzoom** [comment]
Starting to investigate this...  When a spinner button is disabled, that results in a call to `PushButtonModel.setEnabled`, which in turn calls `CallbackTimer.stop`, which stops the timer. In the situation that @phet-steele set up, the problem is that the timer hasn't started running yet, so `CallbackTimer.stop` is a no-op.

**Comment by pixelzoom** [comment]
Spent ~1 hour on this and didn't figure it out.

**Comment by pixelzoom** [comment]
Reproduced in an isolated example. Add this bit of code to any ScreenView subtype's constructor, then press the down (decrement) arrow button.

```js
var NumberSpinner = require( 'REACTANTS_PRODUCTS_AND_LEFTOVERS/common/view/NumberSpinner' );
    var Property = require( 'AXON/Property' );
    var Range = require( 'DOT/Range' );
    var valueRange = new Range( 0, 5 );
    var valueProperty = new Property( valueRange.min + 1 );
    var spinner = new NumberSpinner( valueProperty, valueRange, {
      centerX: this.layoutBounds.centerX,
      bottom: this.layoutBounds.bottom - 20
    } );
    this.addChild( spinner );
```

**Comment by pixelzoom** [comment]
Isolated further to ArrowButton.  Add this bit of code to any ScreenView subtype's constructor, then press the arrow button. The button appears to be disabled when value <= 0, but the arrowButtonListener continues to fire.

```js
var ArrowButton = require( 'SCENERY_PHET/buttons/ArrowButton' );

var value = 1;
var arrowButtonListener = function() {
  value--;
  assert && assert( value >= 0, 'value out of range: ' + value );
  console.log( value );
  arrowButton.enabled = ( value > 0 );
};
var arrowButton = new ArrowButton( 'down', arrowButtonListener, {
  centerX: this.layoutBounds.centerX,
  bottom: this.layoutBounds.bottom - 20
} );
this.addChild( arrowButton );
```

Console output:

```
0
-1
assert.js:22 Assertion failed: value out of range: -1
```

**Comment by pixelzoom** [comment]
Btw... The above only fails if we start with value = MIN_VALUE + 1.  If value is (for example) MIN_VALUE + 2, there's no problem.

**Comment by pixelzoom** [comment]
Isolated further to RectangularPushButton. Add this bit of code to any ScreenView subtype's constructor, then press the arrow button. The button appears to be disabled when value <= 0, but buttonListener continues to fire.

```js
 var Rectangle = require( 'SCENERY/nodes/Rectangle' );
    var RectangularPushButton = require( 'SUN/buttons/RectangularPushButton' );

    var MIN_VALUE = 0;
    var value = 1;
    var buttonListener = function() {
      value--;
      assert && assert( value >= MIN_VALUE, 'value out of range: ' + value );
      console.log( value );
      arrowButton.enabled = ( value > MIN_VALUE );
    };
    var arrowButton = new RectangularPushButton( {
      content: new Rectangle( 0, 0, 20, 10 ),
      listener: buttonListener,
      fireOnHold: true,
      centerX: this.layoutBounds.centerX,
      bottom: this.layoutBounds.bottom - 20
    } );
    this.addChild( arrowButton );
```

Console output:

```
2
1
0
-1
Assertion failed: value out of range: -1
-2
Assertion failed: value out of range: -2
-3
Assertion failed: value out of range: -3
...
```

**Comment by pixelzoom** [comment]
Since this has been isolated to sun, I've created issue https://github.com/phetsims/sun/issues/216 and will continue work there.  I'll leave this open for verification once the bug is fixed.

**Comment by pixelzoom** [comment]
phetsims/sun#216 was a 1-line fix, so I will patch it into sun for the RPAL 1.1 release branch.

**Comment by pixelzoom** [comment]
Patched, sun.  This issue will be verified in 1.1.0-rc.2.
