### ISSUE TITLE
Sandwich/molecule view screen exits boundary of simulation

### ISSUE THREAD

**Issue by bryo5363** [phetsims/reactants-products-and-leftovers#43]
Test device: Acer Aspire R13 (Bryan's personal computer)

Operating System: Windows 10 64 bit

Browser: Chrome 47.0.2526.106 m

Problem description: This issue is related to #42 but as the amount of sandwiches or molecules is increased past 8, the view screen for said molecule/sandwich will disappear from the simulation. Pressing the reset button does not reset the position of the view screens.  

Steps to reproduce:
1) open sim
2) make sure the view screens are not expanded
3) perform #42 until the compressed view screens exit the sim
4) press reset. note that the view screens will not reset to their initial positions. 
Severity:

Screenshots:
This is after pressing the reset button

<img width="753" alt="rpl43" src="https://cloud.githubusercontent.com/assets/7717368/12149866/63b5e43a-b463-11e5-9bd9-580e042abfa2.PNG">

Troubleshooting information (do not edit):
Name: ‪Reactants, Products and Leftovers‬
URL: http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.0-rc.1/reactants-products-and-leftovers_en.html
Version: 1.1.0-rc.1 2015-12-13 01:01:52 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Language: en-US
Window: 1280x595
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"HEAD"},"axon":{"sha":"fffc6c30","branch":"HEAD"},"babel":{"sha":"ac37bd17","branch":"master"},"brand":{"sha":"3b236d6f","branch":"HEAD"},"chipper":{"sha":"6735d265","branch":"HEAD"},"dot":{"sha":"5c39b7d8","branch":"HEAD"},"joist":{"sha":"2a5b44c4","branch":"HEAD"},"kite":{"sha":"84e84bca","branch":"HEAD"},"nitroglycerin":{"sha":"ef8c55a2","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"61a7c5fa","branch":"HEAD"},"reactants-products-and-leftovers":{"sha":"e0aa15ab","branch":"1.1"},"scenery":{"sha":"c0c08ec5","branch":"HEAD"},"scenery-phet":{"sha":"61d8e7ed","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"8d290320","branch":"HEAD"},"tandem":{"sha":"e98bd8c3","branch":"HEAD"},"vegas":{"sha":"e5d21051","branch":"HEAD"},"vibe":{"sha":"40a28182","branch":"HEAD"}}

**Comment by pixelzoom** [comment]
Thanks for reporting. Once bug #42 occurs (exceeding the limitations of the sim), all bets are off with respect to layout - any everything else for that matter. So since this is something that will never occur in practice, it won't be fixed.  Closing.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/tasks/issues/376.
