### ISSUE TITLE
Cursor Enlargement

### ISSUE THREAD

**Issue by phet-steele** [phetsims/reactants-products-and-leftovers#44]
@pixelzoom I have no idea what's going on here, but just moving the cursor from side to side, somewhat rapidly, the cursor may suddenly enlarge quite a bit. It seems entirely random when it happens, and random for how long it lasts. It's happening on any screen, for all browsers on OS X 10.11.2. Dirac specifically if you wan't to try it out.

Video (ignore Ariel's voice :smile:)
https://drive.google.com/file/d/0B3HJopSo_QqLU2daN2RTVDVXZEk/view?usp=sharing

Troubleshooting information (do not edit):
Name: ‪Reactants, Products and Leftovers‬
URL: http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.0-rc.1/reactants-products-and-leftovers_en.html
Version: 1.1.0-rc.1 2015-12-13 01:01:52 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Language: en-US
Window: 1116x592
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"HEAD"},"axon":{"sha":"fffc6c30","branch":"HEAD"},"babel":{"sha":"ac37bd17","branch":"master"},"brand":{"sha":"3b236d6f","branch":"HEAD"},"chipper":{"sha":"6735d265","branch":"HEAD"},"dot":{"sha":"5c39b7d8","branch":"HEAD"},"joist":{"sha":"2a5b44c4","branch":"HEAD"},"kite":{"sha":"84e84bca","branch":"HEAD"},"nitroglycerin":{"sha":"ef8c55a2","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"61a7c5fa","branch":"HEAD"},"reactants-products-and-leftovers":{"sha":"e0aa15ab","branch":"1.1"},"scenery":{"sha":"c0c08ec5","branch":"HEAD"},"scenery-phet":{"sha":"61d8e7ed","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"8d290320","branch":"HEAD"},"tandem":{"sha":"e98bd8c3","branch":"HEAD"},"vegas":{"sha":"e5d21051","branch":"HEAD"},"vibe":{"sha":"40a28182","branch":"HEAD"}}

**Comment by pixelzoom** [comment]
It's a new feature in El Capitan (Mac OS X 10.11), designed to help you find your cursor. See http://www.cnet.com/how-to/wiggle-to-find-your-cursor-in-os-x-el-capitan/.

Closing.

**Comment by phet-steele** [comment]
I was just about to write that and close it myself!

**Comment by pixelzoom** [comment]
Related to RC test https://github.com/phetsims/tasks/issues/376.
