### ISSUE TITLE
remaining 1.1.0 redeploy items

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#45]
RPAL 1.1.0 has been deployed to the PhET website.  Here are the remaining items.

**Design/Admin**

- [x] Rosetta test (Opening sim to trusted translators for beta)
- [x] Check teacher tips are up to date
- [ ] Republish primer video

**Comment by ariel-phet** [comment]
@amyh-phet can you check the teacher tips and make a comment about the primer?

**Comment by amyh-phet** [comment]
Teacher tips are up to date.  Primer video has been reproduced with new bumpers.  I'll check to see when the new primers will be up on the site.

**Comment by ariel-phet** [comment]
I think since the primers are dealt with by separate issues this can be closed
