### ISSUE TITLE
User feedback: alternative to meat sandwich

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/reactants-products-and-leftovers#50]
> My chemistry teacher showed us this simulation in order to introduce the topic of stoichiometry. However, while doing the initial "sandwich" simulation, I was disgusted by the fact that the only alternative sandwich was a meat sandwich. Please change this, and add a vegetarian option for sandwiches as this would appeal to a more diverse crowd.

**Comment by pixelzoom** [comment]
Feel free to customize your sandwich by omitting the meat:

![screenshot_60](https://cloud.githubusercontent.com/assets/3046552/19748549/c084cd88-9b9f-11e6-97d4-12d3191eba41.png)

**Comment by pixelzoom** [comment]
The default sandwich is "Cheese" (no meat) and "Custom" allows you to create a meatless sandwich.

**Comment by pixelzoom** [comment]
Not true. The default sandwich is "Cheese" (no meat) and "Custom" allows you to create a meatless sandwich.

![screenshot_60](https://cloud.githubusercontent.com/assets/3046552/19748549/c084cd88-9b9f-11e6-97d4-12d3191eba41.png)

**Comment by pixelzoom** [comment]
Note that this sim is also vegan friendly - create a custom sandwich and set coefficients for meat and cheese to zero.
