### ISSUE TITLE
layout of equations is messed up

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#54]
This happens in screens 2 and 3.  Here's an example, see the equation at the top:

![screenshot_348](https://user-images.githubusercontent.com/3046552/29147074-0d42fc8a-7d22-11e7-87b4-2b396890eee6.png)

Probably similar to https://github.com/phetsims/ph-scale/issues/70, related to RichText.

**Comment by pixelzoom** [comment]
I suspect that vertically aligning baselines is going to be a lot trickier with RichText.

**Comment by jonathanolson** [comment]
This is a regression, and should be fixed.

The origin Y will still be the baseline of the first line of text.

**Comment by jonathanolson** [comment]
Should be fixed with the above commit, can you verify?

**Comment by pixelzoom** [comment]
👍 Closing.
