### ISSUE TITLE
Sound on Reward Screen Plays Before Image - iPad 2

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/reactants-products-and-leftovers#60]
**Test device:**
iPad 2
**Operating System:**
iOS 9.3.5
**Browser:**
Safari 9
**Problem description:**
For phetsims/QA/issues/162
When a level of the Game screen is beaten the sound effect of cheering will play a few seconds before the actual victory screen is shown.
**Steps to reproduce:**
1. On an iPad 2 iOS 9, enter the Game screen and choose a level.  This was done on level 1.
2. Input the correct answers for all 5 questions.
3. After getting the correct answer on the last question, select next
4. Sound effects will begin playing before the screen changes

**Screenshots:**
https://drive.google.com/file/d/1eWhVYMHk6unaqzWwaCpXTuitRhIwVbyO/view?usp=sharing

**Comment by pixelzoom** [comment]
This has not been a problem in the past, so I suspect that it's related to @jbphet's recent changes to sound.  Let's get him involved.

**Comment by jbphet** [comment]
+1 on what @pixelzoom just said - it will save me time in tracking this down if we know whether it happens on other sims on master as well as currently  published sims.

**Comment by KatieWoe** [comment]
Just tested this on BCE master.  It doesn't seem to occur, or if it does the victory screen appeared quickly enough that I didn't notice it.

**Comment by pixelzoom** [comment]
User interface components (LevelCompletedNode and RewardNode) are now added to the scenegraph before initiating the "cheer" sound. 

@KatieWoe can you please re-test on the device that exhibits the problem?

**Comment by KatieWoe** [comment]
Seems fixed in master

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.  I'll proceed with patching the 1.2 branch.

**Comment by pixelzoom** [comment]
1.2 branch has been patched.  Labeling for regression testing in 1.2.0-rc.2.

**Comment by KatieWoe** [comment]
Looks much better
