### ISSUE TITLE
Layout problem in level-selection screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/reactants-products-and-leftovers#61]
**Test device:**
Mac Laptop
**Operating System:**
Mac OS 10.11.6
**Browser:**
Chrome
**Problem description:**
For phetsims/QA/issues/162
When on screenTest=long and clearing a game, the return to the Game screen causes severe layout issues.
**Steps to reproduce:**
1. While screenTest=long go to the Game screen.  Note that the layout looks ok
2. Select a level.  This screenshot was taken after level 1
3. Beat the level
4. After the victory screen select the button that takes you back to the Game screen

**Screenshots:**
![pastedimage](https://user-images.githubusercontent.com/41024075/43865410-c09b77aa-9b1f-11e8-8449-fc95f27d020e.png)

**Troubleshooting information (do not edit):**
<details>

Name: ‪Reactants, Products and Leftovers‬
URL: https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.0-rc.1/phet/reactants-products-and-leftovers_all_phet.html
Version: 1.2.0-rc.1 2018-08-03 18:35:09 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Language: en-US
Window: 1116x703
Pixel Ratio: 1/1
WebGL: disabled (Could not create a WebGL context, VENDOR = 0xffff, DEVICE = 0xffff, Sandboxed = no, Optimus = no, AMD switchable = no, Reset notification strategy = 0x0000, ErrorMessage = OffscreenContext Creation failed, GpuChannelHost creation failed. Could not create a WebGL context, VENDOR = 0xffff, DEVICE = 0xffff, Sandboxed = no, Optimus = no, AMD switchable = no, Reset notification strategy = 0x0000, ErrorMessage = OffscreenContext Creation failed, GpuChannelHost creation failed. )
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"3feda95c","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"cba50451","branch":"HEAD"},"dot":{"sha":"49561319","branch":"HEAD"},"joist":{"sha":"a7339d37","branch":"HEAD"},"kite":{"sha":"a43e7dd9","branch":"HEAD"},"nitroglycerin":{"sha":"ccaab9cd","branch":"HEAD"},"phet-core":{"sha":"9c242cdc","branch":"HEAD"},"phet-io":{"sha":"a03fa3de","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"f666b06e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b3ca28bf","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"4144509a","branch":"HEAD"},"phet-io-wrappers":{"sha":"a5a4edc5","branch":"HEAD"},"phetcommon":{"sha":"04bc12ce","branch":"HEAD"},"query-string-machine":{"sha":"4178d27a","branch":"HEAD"},"reactants-products-and-leftovers":{"sha":"ff7ba1e5","branch":"HEAD"},"scenery":{"sha":"687654c7","branch":"HEAD"},"scenery-phet":{"sha":"fd193b3a","branch":"HEAD"},"sherpa":{"sha":"79fb5b8c","branch":"HEAD"},"sun":{"sha":"cd84de33","branch":"HEAD"},"tambo":{"sha":"2aac9c19","branch":"HEAD"},"tandem":{"sha":"66d0f519","branch":"HEAD"},"vegas":{"sha":"6b3c902c","branch":"HEAD"},"vibe":{"sha":"960a83ef","branch":"HEAD"}}
</details>

**Comment by pixelzoom** [comment]
I tested 1.2.0-rc.1 on Mac OS 10.11.6 and I could not reproduce this problem. I noticed that I still had Chrome  67.0.3396.99, so I'll update to 68 and try again.

**Comment by pixelzoom** [comment]
After updating to Chrome 68.0.3440.106, I still could not reproduce the problem.  I followed the "Steps to reproduce" exactly, using Level 1.  

@KatieWoe does this problem occur all of the time?

**Comment by pixelzoom** [comment]
There's a slim possibility that I'm not following the steps properly due to different terminology than we typically use. Here's how I interpreted the steps:

- In steps 1 & 4, "Game screen" means the level-selection UI on the _Game_ screen.  
- "Beat the level" means to complete the level with a perfect score. 
- The "victory screen" means the level-complete dialog with reward raining down in the background.  - The "button that takes you back" is the Continue button.  

@KatieWoe is that correct?

**Comment by phet-steele** [comment]
@KatieWoe @pixelzoom I haven't tried this myself, but I'm pretty sure the crucial step that's missing is having Time enabled so that the "Best Time" string is displayed under the level select button.

**Comment by phet-steele** [comment]
> but I'm pretty sure the crucial step that's missing is having Time enabled

Yup this is the culprit 👍

**Comment by KatieWoe** [comment]
Good catch.  I hadn't even realized I'd done that, so I didn't put it in the steps.  Sorry about that.

**Comment by pixelzoom** [comment]
Thanks @phet-steele. Reproduced in master with `?showAnswers&stringTest=long`.   In `LevelSelectionButton`, `bestTimeNode` does not have a `maxWidth` set.  It should be constrained to the width of the button.

**Comment by pixelzoom** [comment]
Fixed in above commit to `VEGAS/LevelSelectionButton`.  Assigning to @KatieWoe to review. 

Assigning to @jonathanolson to decide how to patch this into RC. I'm not able to identify a SHA where this might be patchable. `LevelSelectionButton` is relatively new. In https://github.com/phetsims/vegas/issues/59, `LevelSelectionButton ` replaced and enhanced `LevelSelectionItemNode`.   And it looks like `LevelSelectionItemNode` had this same problem (no `maxWidth` setting for `bestTimeNode`).

**Comment by KatieWoe** [comment]
Issue seems fixed in master.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.  I'll proceed with patching the 1.2 release branch.

**Comment by pixelzoom** [comment]
@jonathanolson FYI, I don't think this needs to be patched in other sims for the same reasons mentioned in https://github.com/phetsims/reactants-products-and-leftovers/issues/59#issuecomment-412298080.

**Comment by pixelzoom** [comment]
Cherry picked in reactants-products-and-leftovers-1.2 branch.

**Comment by KatieWoe** [comment]
Looks good.  Closing
