### ISSUE TITLE
Spinner behaves as if pressed down

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/reactants-products-and-leftovers#62]
**Test device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Chrome
**Problem description:**
For phetsims/QA/issues/162
Discovered while testing fix for phetsims/reactants-products-and-leftovers/issues/61
When using the spinners to select a number of molecules in a level of the game it is possible for the button to become "stuck" and behave as though it is being held down, when it was only clicked.  This happens very inconsistently and I am having trouble reproducing it.  The device has a touchscreen, track pad, and mouse.  I was using the track pad at the time.
**Steps to reproduce:**
1. Go to the game screen
2. Select a level
3. Click one of the buttons on a spinner to increase the number of a given molecule.  The spinner may scroll up to its max value

Troubleshooting information (do not edit):

<details>

Name: ‪Reactants, Products and Leftovers‬
URL: http://phettest.colorado.edu/reactants-products-and-leftovers/reactants-products-and-leftovers_en.html?ea&brand=phet
Version: 1.3.0-dev.0 (require.js)
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
Language: en-US
Window: 1536x737
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
@KatieWoe (and @phet-steele?) Can you please try to reproduce this on something other than the device that you showed me?

**Comment by KatieWoe** [comment]
I'll use this comment to list the devices I've tested so far.  Honestly, I've had some trouble reproducing it on the original device itself.

**Comment by pixelzoom** [comment]
@ariel-phet This problem is not reproducible, so I recommend that label it as deferred and proceed with RC testing https://github.com/phetsims/QA/issues/162.  Do you agree?

**Comment by ariel-phet** [comment]
@KatieWoe @pixelzoom this strikes me as some kind of very device specific issue (track pad doing something odd or such). Considering we have had no such issues reported in other sims with spinners, and no clear reproducible steps at the moment, I am going to go ahead and just close this issue. 

Please proceed with RC testing.
