### ISSUE TITLE
incorrect 'new best time'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#65]
Same issue as https://github.com/phetsims/graphing-lines/issues/111.   Not surprising since they loosely share the same game engine design.

To reproduce:

* complete a level perfectly
* complete the same level perfectly, faster
* try the same level again with no correct answers

**Comment by pixelzoom** [comment]
Fixed in the above commit.

**Comment by KatieWoe** [comment]
Looks fixed on master.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe. Closing.
