### ISSUE TITLE
a11y-related string literals

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#71]
While cleaning up string constants after ES6 module migration, I came across these 3 string literals:

```js
// GameScreen.js
const screenGameDescription = 'Test your knowledge!';

// MoleculesScreen.js
const screenMoleculesDescriptionString = 'Investigate molecules';

// SandwichesScreen.js
const screenSandwichesDescription = 'Interact with sandwiches';
```

All of these are passed to the Screen via option `descriptionContent`, so I'm guessing that this is related to descriptions for a11y.  @jessegreenberg Do you know anything about this?

**Comment by jessegreenberg** [comment]
I am going to remove these, looks like maybe prototype code or testing out Screen.js descriptions for Screen.js that shouldn't be checked in. And RPAL isn't up for description work any time soon.

**Comment by jessegreenberg** [comment]
They have been removed.

**Comment by pixelzoom** [comment]
Excellent, thanks! Closing.
