### ISSUE TITLE
User suggestion: increase H₂ count

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/reactants-products-and-leftovers#72]
The original Java pHet had different numbers as drop-down options in the ammonia production.  The current HTML version maxes out at 8 for hydrogen, whereas the previous version maxed out at 10.  Increasing this to 10 really  helps students to visualize this concept.

**Visuals**
![image](https://user-images.githubusercontent.com/5090275/105214948-e6370500-5b0d-11eb-8d36-acd112b2ab3f.png)
![image](https://user-images.githubusercontent.com/5090275/105214959-ea632280-5b0d-11eb-91f7-ac55a4df9e7e.png)

**Comment by arouinfar** [comment]
@oliver-phet this is not a suggestion we are able to accomodate.

According to the design doc:

> In order to fit the stacked molecules described above and accommodate the reduced vertical space in the first screens, the maximum coefficient was decreased from 10 to 8. Kept max at 8 for the game screen to keep the size of the spinners to single digit and keep molecule size and packing reasonable.

The aspect ratio we design for in HTML5 is a bit shorter than Java, which means we generally have less vertical space to work with when porting a sim. All spinners in the sim have the same maximum of 8. We cannot reasonably increase the maximum number of H2 in this one case. Increasing the max value to 10 in all cases is not feasible and will lead to crowding. Things are already crowded with a max of 8:
![image](https://user-images.githubusercontent.com/8419308/105216939-77a77680-5b10-11eb-924f-9e391827642d.png)

> Increasing this to 10 really helps students to visualize this concept.

I'm not sure that I follow the user's reasoning here. The ammonia reaction has a 1:3 ratio of N2 and H2, so there are two possible ways to avoid leftovers. The other two example reactions both have a 1:2 ratio, so there are four possible spinner combinations that lead to no leftovers. They can also use the custom sandwich option to create whatever reaction ratio they'd like.

**Comment by oliver-phet** [comment]
Replied to user, closing!
