### ISSUE TITLE
Add support for dynamic locale/layout

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#79]
For #77.

Baseline version: https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.3.0-dev.3/phet/reactants-products-and-leftovers_all_phet.html

**Comment by pixelzoom** [comment]
In addition to the layout issues fixed in the above commits...

In the Game screen, the buttons for each challenge (Check, Next,...) do not remain centered in the box.

**Comment by pixelzoom** [comment]
I believe this is done, with the exception of common-code issue https://github.com/phetsims/sun/issues/832.  On-hold until that issue is addressed.

**Comment by pixelzoom** [comment]
Unassigning until https://github.com/phetsims/sun/issues/832 is addressed.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/sun/issues/832 was addressed and is working correctly in this sim.   So work on dynamic locale support is done, and ready for review.  I won't assign it yet, but will instead defer the review until we know what the schedule is for re-releasing this sim.

**Comment by pixelzoom** [comment]
Please verify in https://github.com/phetsims/qa/issues/1159.   Close if OK.

**Comment by Nancy-Salpepi** [comment]
I think this issue can be closed now. Any issues involving dynamic locale/layout have been addressed.
