### ISSUE TITLE
Add gameLevels query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#86]
See GLQueryParameters for an example:

```ts
  // The levels to show in the Line Game screen.
  gameLevels: getGameLevelsSchema( LineGameConstants.NUMBER_OF_GAME_LEVELS ),
```

**Comment by pixelzoom** [comment]
Done. Ready for review when this sim is going to be published again.

**Comment by pixelzoom** [comment]
Please verify in https://github.com/phetsims/qa/issues/1159.   Close if OK.

**Comment by Nancy-Salpepi** [comment]
?gameLevels has been added and working well in 1.3.0-dev.6.
Closing.
