### ISSUE TITLE
Credits for 1.3 release 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#88]
Related to https://github.com/phetsims/reactants-products-and-leftovers/issues/77, we'll need to update the credits for the 1.3 release.

**Comment by pixelzoom** [comment]
Please provide updates to the QA credits for https://github.com/phetsims/qa/issues/1159.   The current credits are shown below.

<img width="714" alt="screenshot_3556" src="https://github.com/user-attachments/assets/a4f77374-2910-4d5a-a76f-c62ba0c42208">

**Comment by KatieWoe** [comment]
Nancy Salpepi, Matthew Moore, and Kathryn Woessner can be added to QA

**Comment by pixelzoom** [comment]
Please specify updates to the QA credits for https://github.com/phetsims/qa/issues/1160 (1.3.0-rc.1)

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/1160 please add Ashton Morris

**Comment by Nancy-Salpepi** [comment]
Credits look good. Closing.
