### ISSUE TITLE
Update Teacher Tips for 1.3 release

### ISSUE THREAD

**Issue by arouinfar** [phetsims/reactants-products-and-leftovers#89]
Related to #77.

We added support for `gameLevels` in #86, so I should add it to the query parameters table in the Teacher Tips.

The .pages file can be found [here](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FReactants%2C%20Products%20and%20Leftovers%20HTML5&viewid=3aa550f4%2Df9ef%2D4871%2Dbcb3%2Da192486a9aaa).

**Comment by arouinfar** [comment]
Teacher Tips are ready to go. Changes include:
* Updated screenshots and realigned callouts
* Added `gameLevels`, `audio`, and `supportsPanAndZoom` query parameters to the table.
* Reorganized sections to optimize page break locations.

When the sim deploys:
- [ ] Verify that newly-added links are functional.
- [ ] Upload Teacher Tips to website.
- [ ] Tag any relevant inclusive features on the admin page.

**Comment by pixelzoom** [comment]
@arouinfar FYI, 1.3.0 has been published.

**Comment by arouinfar** [comment]
Thanks. I completed the TODOs, closing.
