### ISSUE TITLE
location of 'Reset All' button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#9]
As of 1.0.0-dev.10 ...  The 'Reset All' button in the 'Sandwiches' and 'Molecules' screens is currently in the lower-left corner.  In most sims (and the 'Game' screen), it's in the lower-right, but we don't have space there.  Need to decide whether this is an acceptable location, or whether we need to move it. Moving it just about anywhere else will have major layout implications.

**Comment by ariel-phet** [comment]
I just took a look at this on iPad today...it seems we should discuss, on the iPad it looks like plenty of room exists in the lower right hand corner (although this is outside the dev bounds). The dev bounds on this sim do not seem to be matching the iPad bounds. Let's take a look together in person.

**Comment by pixelzoom** [comment]
How's this look? Feels a little crowded in the lower-right to me. We could move everything else slightly left, if you don't mind that the boxes/arrow are not perfectly centered.

http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-dev.22/reactants-products-and-leftovers_en.html

![img_0071](https://cloud.githubusercontent.com/assets/3046552/5625046/d73c578a-952f-11e4-9522-6286138bc6ea.PNG)

**Comment by ariel-phet** [comment]
@pixelzoom I think that is definitely an improvement. Especially since this sim has such a strong left to right flow, I think the reset all button definitely needs to be in that general area of lower-right. Not going to argue that it feels a bit crowded. Let's get @ycarpenterphet to give her opinion if the sim should shift a bit left.

**Comment by pixelzoom** [comment]
If we going to put the "Reset All" button in the lower-right, the first thing I would try is to horizontally center everything else in the space between left edge of the dev bounds and the left edge of the "Reset All" button.  That would look like this:

![screenshot_177](https://cloud.githubusercontent.com/assets/3046552/5631991/3eafdca4-9588-11e4-8ec8-0e9c19c407a4.png)

**Comment by pixelzoom** [comment]
I would also move the 'Reset All' button up a smidge, like this:

![screenshot_178](https://cloud.githubusercontent.com/assets/3046552/5632027/8fe85dbc-9588-11e4-8193-2e1b131f7b08.png)
