### ISSUE TITLE
Update screenshots for 1.3 release

### ISSUE THREAD

**Issue by arouinfar** [phetsims/reactants-products-and-leftovers#90]
While not an absolute requirement for #77, I'd like to update the screenshots for the 1.3 release. The existing screenshots showcase two different versions of the navbar, both outdated, and the inconsistency bothers me.

**Comment by Nancy-Salpepi** [comment]
More than happy to update these for you if you want @arouinfar.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi! I'll take you up on your offer.

The scenarios in the existing screenshot look reasonable, so feel free to retake them or tweak them however you'd like. You can also add a 3rd alternate, if you want (totally optional). Please retake the screen-specific screenshots using `screens` in addition to the ones used for the website.

**Comment by Nancy-Salpepi** [comment]
@arouinfar screenshots are ready for review. If all looks good, please commit (I don't have that permission).

https://o365coloradoedu-my.sharepoint.com/:f:/g/personal/nasa9473_colorado_edu/EjwxYVu-80BBlUIZgMLt_FEBUn_UTT4sC6PmGjGEzUM7Ig

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi, I like your choice for alt3.

The screenshots were updated in the commits referenced above, closing.
