### ISSUE TITLE
Reactants and Products accordion boxes are cut off with smaller window sizes when using ?stringTest=long

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/reactants-products-and-leftovers#93]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0.1

**Browser**
Safari 18.0.1

**Problem description**
For https://github.com/phetsims/qa/issues/1159, with stringTest=long the edges of the Reactants and Products panels are cut off when I narrow the window. I don't see this with ?stringTest=dynamic or ?stringTest=double. 

**Steps to reproduce**
1. Add ?stringTest=long to end of url
2. Go to the Sandwiches or Molecules screen
3. Grab the side of the window and make it smaller

**Visuals**
<img width="1237" alt="Screenshot 2024-10-29 at 8 56 26 AM" src="https://github.com/user-attachments/assets/2c7be7b3-df9f-4c3b-90a8-47b0804dcd92">

**Comment by pixelzoom** [comment]
Reproduced with `?dev&stringTest=long`, see screenshot below.  `maxWidth` for the accordion box titles needs to be reduced.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please review in main. Close if OK.

**Comment by Nancy-Salpepi** [comment]
All fixed! Closing.
