### ISSUE TITLE
"Custom" sandwich not working correctly

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/reactants-products-and-leftovers#94]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0.1

**Browser**
Safari 18.0.1

**Problem description**
For https://github.com/phetsims/qa/issues/1159, on the Sandwich screen with custom selected, adding reactants to the accordion panel BEFORE changing the coefficients in the sandwich equation, leads to no sandwiches being made. This doesn't happen in published. 

**Steps to reproduce**
Here is an example:
1. On the Sandwiches screen select Custom 
2. Add the max amount of each sandwich component
3. Change the coefficient of the cheese to 2 and meat to 1

**Visuals**
<img width="1214" alt="Screenshot 2024-10-29 at 9 38 21 AM" src="https://github.com/user-attachments/assets/bbf3105d-ab1c-4631-b818-3360b85de4ad">

**Comment by pixelzoom** [comment]
Reproduced in main.

If I change any of the "Before" quantities after changing the sandwich coefficients, then everything immediately updates correctly.  So there is probably a missing update call that needs to happen when the coefficients change.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please verify in main. Close if OK.

**Comment by Nancy-Salpepi** [comment]
Working well on main. Closing.
