### ISSUE TITLE
"Best Time" was removed from level-selection buttons

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/reactants-products-and-leftovers#95]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1159
If you achieve a time score on the a level it should then display on the game screen under that level button. However, that is not happening in the new rc.
**Steps to reproduce**
1. Turn the timer on
2. Enter a level and complete it with a perfect score

**Visuals**
![notime](https://github.com/user-attachments/assets/0a0ff116-51af-497b-bdb9-4dbea7118b13)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Reactants, Products and Leftovers‬
URL: https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.3.0-dev.6/phet/reactants-products-and-leftovers_all_phet.html
Version: 1.3.0-dev.6 2024-10-28 21:26:26 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Nancy-Salpepi** [comment]
Published:
<img width="341" alt="Screenshot 2024-10-29 at 3 07 05 PM" src="https://github.com/user-attachments/assets/63fb8b71-9d86-4481-9d0b-58c4fb884bbf">

**Comment by pixelzoom** [comment]
Yikes. Apparently "best time" was totally removed from LevelSelectionButton in https://github.com/phetsims/vegas/commit/f605de47e2d8c5ede7d12b668d637865cda80e5f for https://github.com/phetsims/vegas/issues/120.  I haven't read through that issue, so I don't know what the plan is for how this is supposed to be done.  But this is unlikely to be the only sim that is impacted.

**Comment by pixelzoom** [comment]
>  And this is unlikely to be the only sim that is impacted. 

From the commits associated with https://github.com/phetsims/vegas/issues/120, it looks like "best time" feature is likely to be broken in the following repos:

* balancing-chemical-equations
* build-an-atom
* fractions-common (build-a-fraction, fractions-equality, fractions-intro, fraction-matcher, fractions-mixed-numbers)
* graphing-lines
* reactants-products-and-leftovers

**Comment by pixelzoom** [comment]
According to https://github.com/phetsims/vegas/issues/120#issuecomment-1858310218, it was an intentional design decision, made by a quarum of designers and developers, to remove the "best time" display from LevelSelectionButton specifically and the level-selection user-interface in general. 

So closing this was an intentional design decision, and I'll label the issues as "won't fix".

Assign back to @KatieWoe and @Nancy-Salpepi so that they are aware of this decision, because it will come up in testing of other sims in the future.  Last person assigned please close this issue.

**Comment by KatieWoe** [comment]
Is there another way to display the time, or is the sim changing for this release?

**Comment by pixelzoom** [comment]
Elapsed time is displayed in the scoreboard bar (top of the screen). Elapsed time and Best Time is displayed when you complete a level.  There is no way other way to see your best time(s), which I think is a bit unfortunate/misguided in a game. This makes some of us grumpy, and might be worth revisiting.  But I don't think this this is the forum to reopen that conversation.

**Comment by Nancy-Salpepi** [comment]
Thanks for the update. Closing now.
