### ISSUE TITLE
"No Reaction" text can extend beyond banner height with ?stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/reactants-products-and-leftovers#97]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0.1

**Browser**
Safari 18.0.1

**Problem description**
For https://github.com/phetsims/qa/issues/1160, on the Sandwiches screen with ?stringTest=dynamic, the "No Reaction" text for a custom sandwich doesn't shrink in size as I press the right arrow key. Instead the text will extend beyond the height of the banner. This also occurred in dev.6.

**Steps to reproduce**
1. Add ?stringTest=dynamic to the end of the url
2. Select "custom" radio button
3. Press the right arrow key 3 times

**Visuals**
<img width="1218" alt="Screenshot 2024-11-01 at 10 05 15 AM" src="https://github.com/user-attachments/assets/9f671877-fc65-4fb6-9d6c-2c753461ea42">

**Comment by pixelzoom** [comment]
Good find!  Since "No Reaction" is multiline text, it needs `maxHeight` in addition to `maxWidth`.  Fixed in main and 1.1 brnaches.

@Nancy-Salpepi please verify in main. If it looks OK, change the label to "fixed-awaiting-deploy" for verification in the next RC.

**Comment by Nancy-Salpepi** [comment]
This is fixed on main.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2. Closing.

**Comment by pixelzoom** [comment]
Reopening. This needs to be verified in the next RC test.
